# Generated by Django 5.0.3 on 2024-03-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('difficult', models.IntegerField()),
                ('is_for_kids', models.BooleanField()),
                ('approximate_budget', models.IntegerField()),
                ('start_coordinates', models.TextField()),
                ('end_coordinates', models.TextField()),
                ('link_to_map', models.TextField()),
                ('approximate_duration', models.TextField()),
            ],
        ),
    ]
