# Generated by Django 5.0.3 on 2024-03-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristobject',
            name='distance_from_railwayStation',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
