# Generated by Django 5.0.3 on 2024-04-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_touristobject_distance_from_railwaystation'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristobject',
            name='xCoords',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristobject',
            name='yCoords',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
