# Generated by Django 5.0.3 on 2024-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_touristobject_xcoords_touristobject_ycoords'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristobject',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
