# Generated by Django 5.0.3 on 2024-05-27 09:45

import django.utils.timezone
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_touristobject_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristobject',
            name='array',
            field=django_mysql.models.ListCharField(models.CharField(max_length=25), default=django.utils.timezone.now, max_length=910, size=35),
            preserve_default=False,
        ),
    ]
