# Generated by Django 5.0.3 on 2024-05-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_touristobject_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristobject',
            old_name='approximate_duration',
            new_name='detailedDescription',
        ),
        migrations.RenameField(
            model_name='touristobject',
            old_name='end_coordinates',
            new_name='typeOfRoute',
        ),
        migrations.RemoveField(
            model_name='touristobject',
            name='approximate_budget',
        ),
        migrations.RemoveField(
            model_name='touristobject',
            name='array',
        ),
        migrations.RemoveField(
            model_name='touristobject',
            name='difficult',
        ),
        migrations.RemoveField(
            model_name='touristobject',
            name='distance_from_railwayStation',
        ),
        migrations.RemoveField(
            model_name='touristobject',
            name='is_for_kids',
        ),
        migrations.RemoveField(
            model_name='touristobject',
            name='start_coordinates',
        ),
    ]
