# Generated by Django 5.0.3 on 2024-05-27 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_touristobject_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristobject',
            name='array',
        ),
        migrations.AddField(
            model_name='touristobject',
            name='typeOfRoute',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
