# Generated by Django 5.0.3 on 2024-05-27 11:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_remove_touristobject_array_touristobject_typeofroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristobject',
            name='distance_from_railwayStation',
        ),
        migrations.AddField(
            model_name='touristobject',
            name='full_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
