# Generated by Django 5.0.3 on 2024-05-28 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_touristobject_distance_from_railwaystation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristobject',
            name='image',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
